version: "3.3"

services:
  tf-cli:
    container_name: terraform_state
    build:
      context: .
    volumes:
      # Bind the app directory instead of building into the docker image for re-usability
      - type: bind
        source: ./app
        target: /app
      # Keep Azure config
      - type: volume
        source: azure_config
        target: /root/.azure
    working_dir: /app/src/environments/

volumes:
  azure_config:
